server {
    listen 80;
    index index.php index.html;
    server_name vkb.local;
    # error_log  /var/www/logs/error.log;
    # access_log /var/www/logs/info.log;

    client_max_body_size 50000M;
    
    root /var/www/public;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass dev-vkb-web:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
   
}